# Generated by Django 4.0.6 on 2022-07-28 22:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='choises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(help_text='Ingresa el Nombre del Comprador', max_length=100)),
                ('telefono', models.CharField(help_text='Telefono o Celular', max_length=10)),
                ('municipio', models.CharField(choices=[('SC5xTsAJ', 'SC5xTsAJ'), ('X1JUTm3i', 'X1JUTm3i'), ('SV8OmOZ', 'SV8OmOZ'), ('L4NW1r', 'L4NW1r'), ('eDCADWM', 'eDCADWM')], default=1, max_length=150)),
                ('cp', models.CharField(choices=[('F4v7o', 'F4v7o'), ('A2XAx', 'A2XAx'), ('pJqf0', 'pJqf0'), ('Fk3P1', 'Fk3P1'), ('QH0Io', 'QH0Io'), ('3ByTF', '3ByTF'), ('pjJLI', 'pjJLI'), ('Cfwfz', 'Cfwfz'), ('jpFZd', 'jpFZd'), ('R7YX4', 'R7YX4')], default=1, max_length=150)),
                ('colonia', models.CharField(choices=[('bK72Jy', 'bK72Jy'), ('xprZ300W1S0MK4M', 'xprZ300W1S0MK4M'), ('gGTil72NJRZ1G', 'gGTil72NJRZ1G'), ('X9B2M', 'X9B2M'), ('6qkXKaSYIELEnZ', '6qkXKaSYIELEnZ'), ('zkumqaZ2y2s', 'zkumqaZ2y2s'), ('Xd50I1gsAYAVSJc', 'Xd50I1gsAYAVSJc'), ('x3U4K8DiIu', 'x3U4K8DiIu'), ('ABX0hM4Lrqt', 'ABX0hM4Lrqt'), ('mWMy7YPwH9wXT', 'mWMy7YPwH9wXT'), ('PE2teB2U', 'PE2teB2U')], default=1, max_length=200)),
                ('manzana', models.CharField(help_text='Ingresa la manzana', max_length=5)),
                ('numero_lote', models.CharField(help_text='Ingresa numero de lote', max_length=5)),
                ('m2_lote', models.CharField(default=None, max_length=5)),
                ('costo_del_terreno', models.CharField(default=0, help_text='Costo Terreno', max_length=10)),
                ('deuda_de_terreno', models.CharField(default=0, help_text='Deuda Pendiente', max_length=10)),
                ('a_cuenta_de_terreno', models.CharField(default=0, help_text='A Cuenta de Terreno', max_length=10)),
                ('compromiso_de_pago', models.CharField(default=0, help_text='Compromiso Pago', max_length=10)),
                ('folio_conciliacion', models.CharField(default=0, help_text='Folio', max_length=10)),
                ('cantidad_en_conciliacion', models.CharField(help_text='Cantidad en Conciliacion', max_length=10)),
                ('estatus_pago', models.CharField(choices=[('nuevo', 'Nuevo'), ('corriente', 'Al corriente'), ('atraso', 'Atraso'), ('pendiente', 'Pendiente'), ('disputa', 'Disputa'), ('liquidado', 'Liquidado')], default='nuevo', max_length=20)),
                ('notificaciones', models.CharField(choices=[('recibo', 'Recibo'), ('digital', 'Digital')], default='recibo', max_length=20)),
                ('fecha_de_revision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_de_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('abono_pago', models.CharField(default=0, max_length=7)),
                ('codigo', models.CharField(default='28072022174605ACI', max_length=100)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('estatus_pago',),
            },
        ),
    ]
