# Generated by Django 4.0.6 on 2022-08-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_folio_conciliacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='14082022170548ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('uTPu5H', 'uTPu5H'), ('qWNWHb7V6MR9Y', 'qWNWHb7V6MR9Y'), ('ZCoPAI7Y8', 'ZCoPAI7Y8'), ('LJwH8gYasHsHG7', 'LJwH8gYasHsHG7'), ('5tCBMq', '5tCBMq'), ('oijEReql9SE', 'oijEReql9SE'), ('Lpx2YMyq', 'Lpx2YMyq'), ('O4qqDBhy', 'O4qqDBhy'), ('cAvO4T6ch1Oqo6', 'cAvO4T6ch1Oqo6'), ('liCioNja6q', 'liCioNja6q'), ('o3hy1tso72MBc', 'o3hy1tso72MBc')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('aHwWY', 'aHwWY'), ('nDNHd', 'nDNHd'), ('gjMfu', 'gjMfu'), ('KkXY4', 'KkXY4'), ('B4T5e', 'B4T5e'), ('5oqLJ', '5oqLJ'), ('vuSaM', 'vuSaM'), ('dglrK', 'dglrK'), ('rtIgr', 'rtIgr'), ('mr9o8', 'mr9o8')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('Cvx0U', 'Cvx0U'), ('Z3i6lfg', 'Z3i6lfg'), ('rRIBoN3pGAykbWM', 'rRIBoN3pGAykbWM'), ('CUr5Ck7', 'CUr5Ck7'), ('1ygS9MY', '1ygS9MY')], default=1, max_length=150),
        ),
    ]
