# Generated by Django 4.0.6 on 2022-08-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_codigo_alter_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='14082022171223ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('HyExiMdxHss', 'HyExiMdxHss'), ('0LKXXjC1DFm', '0LKXXjC1DFm'), ('X87ZLhk', 'X87ZLhk'), ('u3Xwq', 'u3Xwq'), ('atkezILdfC', 'atkezILdfC'), ('wjq0qY6H', 'wjq0qY6H'), ('G8bYw', 'G8bYw'), ('fD2dRf', 'fD2dRf'), ('4sR6F6F6V0xC', '4sR6F6F6V0xC'), ('WaCLNucbZOgwN', 'WaCLNucbZOgwN')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('rsf9r', 'rsf9r'), ('JUFMg', 'JUFMg'), ('yZJLE', 'yZJLE'), ('wAft9', 'wAft9'), ('CKCHq', 'CKCHq'), ('cmL22', 'cmL22'), ('ZalHE', 'ZalHE'), ('XENqW', 'XENqW'), ('Xaggx', 'Xaggx'), ('sJMSF', 'sJMSF')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('iEkTLRKIYn', 'iEkTLRKIYn'), ('eTy1FFbCIQ6', 'eTy1FFbCIQ6'), ('yqqVUeR', 'yqqVUeR'), ('U0wsYJwMK0Ib', 'U0wsYJwMK0Ib')], default=1, max_length=150),
        ),
    ]
