# Generated by Django 4.0.6 on 2022-08-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_codigo_alter_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='14082022184946ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('AUsSMkIyZ', 'AUsSMkIyZ'), ('EZIsWKe', 'EZIsWKe'), ('2wGUJLr', '2wGUJLr'), ('QFgempKaLXIRVq', 'QFgempKaLXIRVq'), ('l8SMyaqs98O', 'l8SMyaqs98O'), ('OAeCHY', 'OAeCHY'), ('xoaGB7ks3', 'xoaGB7ks3'), ('pRYLiaDgtigyHg', 'pRYLiaDgtigyHg'), ('qxKkLc7T4U0', 'qxKkLc7T4U0'), ('1lBzpewqqCK1Rm', '1lBzpewqqCK1Rm')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('O0ruu', 'O0ruu'), ('bk1Z6', 'bk1Z6'), ('G58Bl', 'G58Bl'), ('TQJ9I', 'TQJ9I'), ('rKx6f', 'rKx6f'), ('ukbga', 'ukbga'), ('CKfaY', 'CKfaY'), ('BZfN1', 'BZfN1'), ('xyPFB', 'xyPFB'), ('q9re2', 'q9re2')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('bzalMA4fEK', 'bzalMA4fEK'), ('yBahKGaqFsW', 'yBahKGaqFsW'), ('abMREw7hOdc', 'abMREw7hOdc'), ('xvwpVRxkI2EpkE', 'xvwpVRxkI2EpkE')], default=1, max_length=150),
        ),
    ]
