# Generated by Django 4.0.6 on 2022-08-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_cliente_codigo_alter_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='14082022190239ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('vUHbBJS8', 'vUHbBJS8'), ('WGAoXlJFH', 'WGAoXlJFH'), ('rRZ9OvAoCaGItb', 'rRZ9OvAoCaGItb'), ('saEbPS1', 'saEbPS1'), ('v0JiI', 'v0JiI'), ('Q39AF', 'Q39AF'), ('85gndijyXP', '85gndijyXP'), ('pt0b8LHAejc', 'pt0b8LHAejc'), ('zTLDpUfX', 'zTLDpUfX'), ('N7G0sEPhKOs5', 'N7G0sEPhKOs5'), ('jodpwGMsmWMzOi6', 'jodpwGMsmWMzOi6')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('PBljE', 'PBljE'), ('A7RBf', 'A7RBf'), ('K8jCe', 'K8jCe'), ('uSFod', 'uSFod'), ('UY8B4', 'UY8B4'), ('kR9pP', 'kR9pP'), ('VHgEg', 'VHgEg'), ('IB4Nm', 'IB4Nm'), ('ETL4B', 'ETL4B'), ('p2brM', 'p2brM')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('u2E0OkJamc5ZHd', 'u2E0OkJamc5ZHd'), ('Rk8LqpRS69j', 'Rk8LqpRS69j'), ('uP9LZAyGgN', 'uP9LZAyGgN')], default=1, max_length=150),
        ),
    ]
