# Generated by Django 4.0.6 on 2022-08-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_cliente_codigo_alter_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='14082022190338ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('5fcVJf', '5fcVJf'), ('45m6XCmW5CNLr', '45m6XCmW5CNLr'), ('XrS1KjSW', 'XrS1KjSW'), ('Yqwhx', 'Yqwhx'), ('dNi9P', 'dNi9P'), ('fUzoAi', 'fUzoAi'), ('VsnxdLqUHgar', 'VsnxdLqUHgar'), ('AGnlk46j', 'AGnlk46j'), ('rKtefc0w', 'rKtefc0w'), ('MIk4WjGrjMpKz2', 'MIk4WjGrjMpKz2')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('2GJ9h', '2GJ9h'), ('lvf6I', 'lvf6I'), ('boi6i', 'boi6i'), ('CFBNE', 'CFBNE'), ('7x2pX', '7x2pX'), ('aeLY3', 'aeLY3'), ('qIF5S', 'qIF5S'), ('gDE1C', 'gDE1C'), ('dP1R7', 'dP1R7'), ('qxKdv', 'qxKdv')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('h9R9QXK3xmKS5N', 'h9R9QXK3xmKS5N'), ('xZteEgcFfhcoin', 'xZteEgcFfhcoin')], default=1, max_length=150),
        ),
    ]
