# Generated by Django 4.0.6 on 2022-08-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_alter_cliente_codigo_alter_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='14082022190435ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('cSe6t', 'cSe6t'), ('0ts7coKf02t9j', '0ts7coKf02t9j'), ('xD2Ftji', 'xD2Ftji'), ('dlu58wyER1q4G', 'dlu58wyER1q4G'), ('TRbDlTuOa1MXtue', 'TRbDlTuOa1MXtue'), ('IX4lhPYI', 'IX4lhPYI'), ('IQgVH', 'IQgVH'), ('cHMoy', 'cHMoy'), ('OZm84vh0fVfy2q', 'OZm84vh0fVfy2q'), ('0k8LQRm', '0k8LQRm'), ('H6o0ZA520htZJ', 'H6o0ZA520htZJ'), ('PE4ibDW', 'PE4ibDW'), ('yKuDqSU1gvYLurM', 'yKuDqSU1gvYLurM'), ('0uc8qTuhGTqY', '0uc8qTuhGTqY')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('bcu7e', 'bcu7e'), ('iK0Zo', 'iK0Zo'), ('MUjFB', 'MUjFB'), ('vB9Wc', 'vB9Wc'), ('PmKep', 'PmKep'), ('mHlQi', 'mHlQi'), ('WezA5', 'WezA5'), ('pH2ho', 'pH2ho'), ('Bx3p5', 'Bx3p5'), ('9obb6', '9obb6')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('I1D6nV', 'I1D6nV'), ('P5GhEjsuOq6d', 'P5GhEjsuOq6d')], default=1, max_length=150),
        ),
    ]
