# Generated by Django 4.0.6 on 2022-08-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_remove_cliente_deuda_de_terreno_alter_cliente_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='deuda_de_terreno',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='a_cuenta_de_terreno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='14082022193942ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('k9St24GASfX', 'k9St24GASfX'), ('rI5Pnajx', 'rI5Pnajx'), ('UNwbw', 'UNwbw'), ('9KC2cS', '9KC2cS'), ('20zxGxIwGVXN', '20zxGxIwGVXN'), ('HkExTpYUgLVFx', 'HkExTpYUgLVFx'), ('h3u9nj', 'h3u9nj'), ('boqmkhoRS0', 'boqmkhoRS0'), ('0zAnqgieN2l', '0zAnqgieN2l')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('hcFDw', 'hcFDw'), ('CNIWa', 'CNIWa'), ('OY1Pg', 'OY1Pg'), ('YLWYz', 'YLWYz'), ('pf9u8', 'pf9u8'), ('faaBD', 'faaBD'), ('lCIoV', 'lCIoV'), ('miRYe', 'miRYe'), ('rS4uq', 'rS4uq'), ('RIzhm', 'RIzhm')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('t5dQ6Y5PMb', 't5dQ6Y5PMb'), ('SxMvRhp2Wr8DHL', 'SxMvRhp2Wr8DHL'), ('XMYiqFwflFx', 'XMYiqFwflFx'), ('xKCLTj3gCyoT5VQ', 'xKCLTj3gCyoT5VQ'), ('AzDwx5', 'AzDwx5'), ('Jd2WmoGERD', 'Jd2WmoGERD')], default=1, max_length=150),
        ),
    ]
