# Generated by Django 4.0.6 on 2022-08-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_cliente_deuda_de_terreno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='14082022204020ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('mLYHYKtApE4u', 'mLYHYKtApE4u'), ('kHZ0VFO', 'kHZ0VFO'), ('cYQt76G', 'cYQt76G'), ('GxNYQewQGm', 'GxNYQewQGm'), ('nmt0YrLLA6c81Z', 'nmt0YrLLA6c81Z'), ('uw27BVc', 'uw27BVc'), ('JAAy6R8oTP9t', 'JAAy6R8oTP9t')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('Cw7lQ', 'Cw7lQ'), ('oL6PX', 'oL6PX'), ('Z6qG7', 'Z6qG7'), ('sWDOh', 'sWDOh'), ('QBAIe', 'QBAIe'), ('X2ZPz', 'X2ZPz'), ('FrC0x', 'FrC0x'), ('5Y5dD', '5Y5dD'), ('sLrH0', 'sLrH0'), ('j1GM1', 'j1GM1')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('mEXs2OVIZ', 'mEXs2OVIZ'), ('jlyeX8TPMt', 'jlyeX8TPMt'), ('K9utKg37', 'K9utKg37'), ('AZxyV', 'AZxyV')], default=1, max_length=150),
        ),
    ]
