# Generated by Django 4.0.6 on 2022-08-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_alter_cliente_codigo_alter_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='14082022204542ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('5XGkP', '5XGkP'), ('kJ4Sgxxs7EglIcb', 'kJ4Sgxxs7EglIcb'), ('VRHYXbZKewWNp', 'VRHYXbZKewWNp'), ('lbHFeh', 'lbHFeh'), ('rYedPSl', 'rYedPSl'), ('KoZSAjt', 'KoZSAjt'), ('S0aPG', 'S0aPG'), ('Mxi0Gh6', 'Mxi0Gh6'), ('u36JVgX3TkS7cN', 'u36JVgX3TkS7cN')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('Mq5BX', 'Mq5BX'), ('I4Hr0', 'I4Hr0'), ('atjG3', 'atjG3'), ('Wsdz4', 'Wsdz4'), ('Mwbrw', 'Mwbrw'), ('qhXn2', 'qhXn2'), ('eQNZh', 'eQNZh'), ('xlh9e', 'xlh9e'), ('tlsoZ', 'tlsoZ'), ('1CItw', '1CItw')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('aKTPibCEMhKR0a', 'aKTPibCEMhKR0a'), ('WxEszgLSBk0YOP', 'WxEszgLSBk0YOP')], default=1, max_length=150),
        ),
    ]
