# Generated by Django 4.0.6 on 2022-08-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_alter_cliente_codigo_alter_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='14082022204802ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('P9M0R9IHj', 'P9M0R9IHj'), ('OLDbe7O', 'OLDbe7O'), ('uBT5T4BnJ2eKrd', 'uBT5T4BnJ2eKrd'), ('ldYUOydAwOFC', 'ldYUOydAwOFC'), ('8Pyh3', '8Pyh3'), ('0FdmvprAQ', '0FdmvprAQ'), ('Rvjyh', 'Rvjyh'), ('91Uv5g', '91Uv5g'), ('9c8vH0BoP', '9c8vH0BoP'), ('e57k2XFN6olhMgY', 'e57k2XFN6olhMgY')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('73u76', '73u76'), ('nHtzu', 'nHtzu'), ('LfnMf', 'LfnMf'), ('J10Xs', 'J10Xs'), ('Da1ke', 'Da1ke'), ('PhS1Z', 'PhS1Z'), ('UnsPw', 'UnsPw'), ('nC18X', 'nC18X'), ('Kclsm', 'Kclsm'), ('qGDS2', 'qGDS2')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('iNcbH1IGuGYiST', 'iNcbH1IGuGYiST'), ('CkI9GfwAksy', 'CkI9GfwAksy'), ('GPQkY', 'GPQkY'), ('KXoCFOsggXY4C', 'KXoCFOsggXY4C'), ('etRS9pVBxzgPW', 'etRS9pVBxzgPW')], default=1, max_length=150),
        ),
    ]
