# Generated by Django 4.0.6 on 2022-08-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_alter_cliente_codigo_alter_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('fecha_de_pago', models.DateTimeField(auto_now_add=True)),
                ('comprobante_de_pago', models.FileField(null=True, upload_to='clientes/filesbk/')),
                ('nombre_cliente_pago', models.CharField(max_length=100, null=True)),
                ('codigo', models.CharField(max_length=30, null=True)),
            ],
            options={
                'ordering': ('fecha_de_pago',),
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='a_cuenta_de_terreno',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('BFVAjl2BQQ', 'BFVAjl2BQQ'), ('WLqPv3VG', 'WLqPv3VG'), ('F4FmqYZe', 'F4FmqYZe'), ('FJT8tj3', 'FJT8tj3'), ('eeMNEbo', 'eeMNEbo'), ('aGX33p7mkixEiE', 'aGX33p7mkixEiE'), ('1dWAV9G9E83ySb', '1dWAV9G9E83ySb'), ('hL7fvy', 'hL7fvy'), ('9kKi7Y06d', '9kKi7Y06d'), ('XsWC2hzaa', 'XsWC2hzaa')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('cAozU', 'cAozU'), ('ZxHhc', 'ZxHhc'), ('geAEw', 'geAEw'), ('1bKCI', '1bKCI'), ('YV3SX', 'YV3SX'), ('x6OBL', 'x6OBL'), ('pvFrE', 'pvFrE'), ('8RPF5', '8RPF5'), ('Q8y0K', 'Q8y0K'), ('t1afE', 't1afE')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('gjWXYUXVBx8NU4O', 'gjWXYUXVBx8NU4O')], default=1, max_length=150),
        ),
    ]
