# Generated by Django 4.0.6 on 2022-08-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0022_pago_remove_cliente_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estatus_pago2',
            field=models.CharField(default='nuevo', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('44SrHU3s5U1Ow', '44SrHU3s5U1Ow'), ('pKglIXo', 'pKglIXo'), ('HnqZ9ZqpW7pAj9', 'HnqZ9ZqpW7pAj9'), ('gh5CQ', 'gh5CQ'), ('ctIMxxJABg94Dr9', 'ctIMxxJABg94Dr9'), ('keaR9SsWxEOUWs1', 'keaR9SsWxEOUWs1'), ('H9kNks4Jo6q', 'H9kNks4Jo6q'), ('uH658yoyzIAzt', 'uH658yoyzIAzt'), ('Rt62hkOB', 'Rt62hkOB'), ('DIljv72ARiJ8f', 'DIljv72ARiJ8f'), ('5Bc6I', '5Bc6I'), ('c7pemZL1', 'c7pemZL1'), ('rBjkOanDmY', 'rBjkOanDmY'), ('zau2M', 'zau2M')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('JXUws', 'JXUws'), ('lZakc', 'lZakc'), ('o4xbP', 'o4xbP'), ('gzBa1', 'gzBa1'), ('rVWTQ', 'rVWTQ'), ('f0Hh9', 'f0Hh9'), ('gYqwH', 'gYqwH'), ('o8E4v', 'o8E4v'), ('CnqyA', 'CnqyA'), ('iqzh2', 'iqzh2')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('m7JnOAwLb', 'm7JnOAwLb'), ('BRYN1bRDer9WahM', 'BRYN1bRDer9WahM'), ('qeWFkA', 'qeWFkA')], default=1, max_length=150),
        ),
    ]
