# Generated by Django 4.0.6 on 2022-08-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_pago_estatus_pago2_alter_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('UNfNta7PaQMwx', 'UNfNta7PaQMwx'), ('j5R5qfSV9c7GWy', 'j5R5qfSV9c7GWy'), ('S9ZgBfpSXD4wtI', 'S9ZgBfpSXD4wtI'), ('Y1mVOQvgYzs1YB', 'Y1mVOQvgYzs1YB'), ('puf96wjNuTzoOj', 'puf96wjNuTzoOj'), ('dHK1y4RTxDHSyo', 'dHK1y4RTxDHSyo'), ('5uuBGAK56GQ4tZ', '5uuBGAK56GQ4tZ'), ('qNFUWMOTBu', 'qNFUWMOTBu')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('1WeuZ', '1WeuZ'), ('pwhYp', 'pwhYp'), ('aMgCU', 'aMgCU'), ('QDzHT', 'QDzHT'), ('nwD4l', 'nwD4l'), ('8j13Q', '8j13Q'), ('vjWIq', 'vjWIq'), ('Trnwp', 'Trnwp'), ('tOI66', 'tOI66'), ('PW85q', 'PW85q')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('EZEBNkLIpn', 'EZEBNkLIpn')], default=1, max_length=150),
        ),
    ]
