# Generated by Django 4.0.6 on 2022-08-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_alter_cliente_colonia_alter_cliente_cp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('vFy7WaoOW4', 'vFy7WaoOW4'), ('kF9fnbpTdL0zPu', 'kF9fnbpTdL0zPu'), ('4zitpqJ5I', '4zitpqJ5I'), ('QLRFOYCmNzPUbp', 'QLRFOYCmNzPUbp'), ('18J7NE48', '18J7NE48'), ('VQzN8a', 'VQzN8a'), ('5F8uhJuj9d', '5F8uhJuj9d'), ('Ub0DV6xNMaAX', 'Ub0DV6xNMaAX'), ('uF1eXJK5MXDn', 'uF1eXJK5MXDn'), ('gZagA9oNumUn', 'gZagA9oNumUn')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('CGztb', 'CGztb'), ('4ibwP', '4ibwP'), ('Ny5F8', 'Ny5F8'), ('5C4dd', '5C4dd'), ('h7S06', 'h7S06'), ('9MQ0N', '9MQ0N'), ('vB177', 'vB177'), ('yHuor', 'yHuor'), ('F4pXj', 'F4pXj'), ('k6CrL', 'k6CrL')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('EAibFnDQROnN', 'EAibFnDQROnN'), ('cu3pJUUpSwg8Af', 'cu3pJUUpSwg8Af'), ('OWaHvSpeEm', 'OWaHvSpeEm'), ('EvHBQa65', 'EvHBQa65')], default=1, max_length=150),
        ),
    ]
