# Generated by Django 4.0.6 on 2022-08-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_alter_cliente_colonia_alter_cliente_cp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('ycJZRmHlQ9y', 'ycJZRmHlQ9y'), ('wNTQ5EzsdtgDt', 'wNTQ5EzsdtgDt'), ('EGntOE', 'EGntOE'), ('qtagLyFfaUqSJ', 'qtagLyFfaUqSJ'), ('0RmiM2', '0RmiM2'), ('YO7luh', 'YO7luh'), ('Kn6jo9dD', 'Kn6jo9dD'), ('PiJdEYaY', 'PiJdEYaY')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('FOUtg', 'FOUtg'), ('BemNo', 'BemNo'), ('I0zal', 'I0zal'), ('SCfx2', 'SCfx2'), ('3bY9y', '3bY9y'), ('K5kQ8', 'K5kQ8'), ('UcmCu', 'UcmCu'), ('0Xr0j', '0Xr0j'), ('4HFOU', '4HFOU'), ('Q3hbq', 'Q3hbq')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('nbyqKti', 'nbyqKti'), ('EZ29lR9B', 'EZ29lR9B'), ('S18LO49DYALF', 'S18LO49DYALF'), ('c5pt0Owr4z', 'c5pt0Owr4z')], default=1, max_length=150),
        ),
    ]
