# Generated by Django 4.0.6 on 2022-08-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0027_alter_pago_options_alter_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ('fecha_de_pago',)},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('wbckBig5vU', 'wbckBig5vU'), ('moPB8rrXLHuz', 'moPB8rrXLHuz'), ('yv0nhduDvNe', 'yv0nhduDvNe'), ('YjiJjXWf5AVOg', 'YjiJjXWf5AVOg'), ('zMcvfv2oKQhf590', 'zMcvfv2oKQhf590'), ('1giGuAnKZ', '1giGuAnKZ'), ('YnbzvDYRZZuAa3', 'YnbzvDYRZZuAa3'), ('nyJLEaRtip3', 'nyJLEaRtip3')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('Ui1JU', 'Ui1JU'), ('fKd1F', 'fKd1F'), ('vKcGM', 'vKcGM'), ('fqXJp', 'fqXJp'), ('urDL5', 'urDL5'), ('SpLXk', 'SpLXk'), ('Cd78k', 'Cd78k'), ('qdRvS', 'qdRvS'), ('ymSM1', 'ymSM1'), ('ct4px', 'ct4px')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('SXYW2WYMFL', 'SXYW2WYMFL'), ('0v2HmyCbA43v', '0v2HmyCbA43v'), ('GVjiDep3', 'GVjiDep3'), ('KJBwqZmUgCY', 'KJBwqZmUgCY'), ('9g8Lcu8E', '9g8Lcu8E'), ('NGeuVd', 'NGeuVd'), ('KtiuZWKA', 'KtiuZWKA')], default=1, max_length=150),
        ),
    ]
