# Generated by Django 4.0.6 on 2022-08-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0028_alter_pago_options_alter_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ('-fecha_de_pago',)},
        ),
        migrations.AddField(
            model_name='pago',
            name='abono_cliente',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('wukV4mYMtPn', 'wukV4mYMtPn'), ('bErOUxm9Re5H', 'bErOUxm9Re5H'), ('kcBWPEyyz2W', 'kcBWPEyyz2W'), ('tEI9f6fwhYcE', 'tEI9f6fwhYcE'), ('z0tIeZej8Fjnyu', 'z0tIeZej8Fjnyu'), ('1gyvJu9iGMS', '1gyvJu9iGMS'), ('s4RINAHQ6a', 's4RINAHQ6a'), ('USnCn3rHllthz', 'USnCn3rHllthz'), ('ETnss', 'ETnss'), ('MX5tENeAwNZ92n', 'MX5tENeAwNZ92n')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('OYmRD', 'OYmRD'), ('E6v1g', 'E6v1g'), ('XFBuz', 'XFBuz'), ('9KOt0', '9KOt0'), ('wLg8G', 'wLg8G'), ('KrFRi', 'KrFRi'), ('GR2it', 'GR2it'), ('Kyb5C', 'Kyb5C'), ('gwxGX', 'gwxGX'), ('BLC3g', 'BLC3g')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('zcggX0', 'zcggX0'), ('f5tapF2aXzm3mf', 'f5tapF2aXzm3mf'), ('AsYxYpbHpQx', 'AsYxYpbHpQx')], default=1, max_length=150),
        ),
    ]
