# Generated by Django 4.0.6 on 2022-08-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0029_alter_pago_options_pago_abono_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('SPJ5jCfsA', 'SPJ5jCfsA'), ('onNtO8ZFHG3', 'onNtO8ZFHG3'), ('1GavhL72Cs2rQC', '1GavhL72Cs2rQC'), ('3b9LIO', '3b9LIO'), ('g8Q9QbnN', 'g8Q9QbnN'), ('bb7AZjZ97bf9Xq', 'bb7AZjZ97bf9Xq'), ('PbmkKg0V', 'PbmkKg0V')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('R0eEB', 'R0eEB'), ('NdqSc', 'NdqSc'), ('VU4vl', 'VU4vl'), ('VSrs2', 'VSrs2'), ('CBRVu', 'CBRVu'), ('n2PnQ', 'n2PnQ'), ('jDWDf', 'jDWDf'), ('VLF5m', 'VLF5m'), ('YMkMK', 'YMkMK'), ('4m0wR', '4m0wR')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('9dBhk', '9dBhk'), ('OTbQ8lXf0es', 'OTbQ8lXf0es'), ('XdwnkJB', 'XdwnkJB'), ('CEW3JI', 'CEW3JI'), ('QyDTp2fb3aGyZ1G', 'QyDTp2fb3aGyZ1G')], default=1, max_length=150),
        ),
    ]
