# Generated by Django 4.0.6 on 2022-08-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0031_cliente_forma_de_pago_alter_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('m9slnoGh', 'm9slnoGh'), ('Wd7f1C1rknK', 'Wd7f1C1rknK'), ('8Z0Hj', '8Z0Hj'), ('8c4kmEYo9i4K', '8c4kmEYo9i4K'), ('kZKrgO7Fnmc', 'kZKrgO7Fnmc'), ('Wi9vk', 'Wi9vk'), ('qLr5K', 'qLr5K'), ('6SrbXY6', '6SrbXY6'), ('WVO7VFlHwg', 'WVO7VFlHwg')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('NZet1', 'NZet1'), ('ubYw6', 'ubYw6'), ('49PHD', '49PHD'), ('Z32Tx', 'Z32Tx'), ('AWsY4', 'AWsY4'), ('ZIThW', 'ZIThW'), ('6ICgD', '6ICgD'), ('WPa2r', 'WPa2r'), ('cwoW8', 'cwoW8'), ('Jathl', 'Jathl')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='forma_de_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('dnHi7d', 'dnHi7d'), ('j2r1nX', 'j2r1nX'), ('hqKIO9mY', 'hqKIO9mY'), ('TIelmA', 'TIelmA'), ('2ZavUqclxQL7qqO', '2ZavUqclxQL7qqO')], default=1, max_length=150),
        ),
    ]
