# Generated by Django 4.0.6 on 2022-08-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0032_alter_cliente_colonia_alter_cliente_cp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='18082022165815ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('7DE03P8', '7DE03P8'), ('VYRQiTLO2Xj0F8', 'VYRQiTLO2Xj0F8'), ('8WZD1cHGY', '8WZD1cHGY'), ('9BTzev4', '9BTzev4'), ('POiHce', 'POiHce'), ('LAI1kzfxnQ', 'LAI1kzfxnQ'), ('sdaSN', 'sdaSN'), ('jzbV8z0YKsT', 'jzbV8z0YKsT'), ('8L2WJjUCRLc', '8L2WJjUCRLc'), ('GXsBDSsw6', 'GXsBDSsw6')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('LCgF5', 'LCgF5'), ('aNkiA', 'aNkiA'), ('0wY1U', '0wY1U'), ('i6re4', 'i6re4'), ('9o4yN', '9o4yN'), ('t6Q79', 't6Q79'), ('KmTBx', 'KmTBx'), ('S92bj', 'S92bj'), ('jwryP', 'jwryP'), ('yvW9Y', 'yvW9Y')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('mgrdN82rVGF', 'mgrdN82rVGF'), ('Gf9At9nCqLHOI', 'Gf9At9nCqLHOI')], default=1, max_length=150),
        ),
    ]
