# Generated by Django 4.0.6 on 2022-08-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0033_cliente_codigo_alter_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='18082022170010ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('IpmxBl7dSP', 'IpmxBl7dSP'), ('CjJou3Oxwa5WU', 'CjJou3Oxwa5WU'), ('Sdzo17J9pRc', 'Sdzo17J9pRc'), ('ATAAXObZDX8U26', 'ATAAXObZDX8U26'), ('8WhG1NUT', '8WhG1NUT'), ('LEtMB6oFMAO', 'LEtMB6oFMAO'), ('J4QH4rHsvSYv', 'J4QH4rHsvSYv'), ('jxPEH', 'jxPEH')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('NHhQu', 'NHhQu'), ('AC5CV', 'AC5CV'), ('JEd4S', 'JEd4S'), ('051GL', '051GL'), ('jxGZs', 'jxGZs'), ('uLJd0', 'uLJd0'), ('zWfZM', 'zWfZM'), ('QcHbB', 'QcHbB'), ('4yVKc', '4yVKc'), ('5eCbo', '5eCbo')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('jtOk3f7h', 'jtOk3f7h'), ('4otta6NGS', '4otta6NGS'), ('2g2yrg', '2g2yrg')], default=1, max_length=150),
        ),
    ]
