# Generated by Django 4.0.6 on 2022-08-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0035_alter_cliente_a_cuenta_de_terreno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='30082022145234ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(choices=[('YmFD21Wf', 'YmFD21Wf'), ('mPjJQerRCq', 'mPjJQerRCq'), ('hwxfw6x', 'hwxfw6x'), ('w9LOiUMV', 'w9LOiUMV'), ('fOHJQ2Qg', 'fOHJQ2Qg'), ('kFUv1JYSqI', 'kFUv1JYSqI'), ('fYnn5wl', 'fYnn5wl')], max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(choices=[('tv8p5', 'tv8p5'), ('zK6uO', 'zK6uO'), ('tdMyq', 'tdMyq'), ('73DBl', '73DBl'), ('mkMQ9', 'mkMQ9'), ('MsncI', 'MsncI'), ('nr9OI', 'nr9OI'), ('iQNyr', 'iQNyr'), ('G8VsE', 'G8VsE'), ('N2OZ8', 'N2OZ8'), ('6wNOh', '6wNOh'), ('engEZ', 'engEZ'), ('0idh8', '0idh8')], max_length=350),
        ),
    ]
