# Generated by Django 4.0.6 on 2022-09-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0036_alter_cliente_codigo_alter_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='01092022142217ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(help_text='Ingresa la Colonia', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(help_text='Ingresa Codigo Postal', max_length=6),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante_de_pago',
            field=models.FileField(null=True, upload_to='static/images/'),
        ),
    ]
