# Generated by Django 4.0.6 on 2022-09-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0039_alter_cliente_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='a_cuenta_de_terreno',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cantidad_en_conciliacion',
            field=models.IntegerField(blank=True, default=0, help_text='Cantidad en Conciliacion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='23092022183928ACI', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(blank=True, help_text='Ingresa la Colonia', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='compromiso_de_pago',
            field=models.IntegerField(blank=True, default=0, help_text='Compromiso Pago'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='costo_del_terreno',
            field=models.IntegerField(blank=True, default=0, help_text='Costo Terreno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(blank=True, help_text='Ingresa Codigo Postal', max_length=6),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='deuda_de_terreno',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='m2_lote',
            field=models.CharField(blank=True, default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='manzana',
            field=models.IntegerField(blank=True, default=0, help_text='Ingresa la manzana'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_lote',
            field=models.IntegerField(blank=True, default=0, help_text='Ingresa numero de lote'),
        ),
    ]
