# Generated by Django 4.0.6 on 2022-09-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0040_alter_cliente_a_cuenta_de_terreno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='23092022184053ACI', max_length=100),
        ),
    ]
