# Generated by Django 4.0.6 on 2022-09-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0041_alter_cliente_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='27092022191904ACI', max_length=100),
        ),
    ]
