# Generated by Django 4.0.6 on 2022-08-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ('fecha_de_pago',)},
        ),
        migrations.RemoveField(
            model_name='pago',
            name='id_cliente',
        ),
    ]
