# Generated by Django 4.0.6 on 2022-08-14 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_codigo_alter_cliente_colonia_and_more'),
        ('pago', '0002_alter_pago_options_remove_pago_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
