# Generated by Django 4.0.6 on 2022-08-14 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_codigo_alter_cliente_colonia_and_more'),
        ('pago', '0003_pago_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='comprobante_de_pago',
        ),
        migrations.AlterField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='clientes.cliente'),
        ),
    ]
