# Generated by Django 4.0.6 on 2022-08-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0004_remove_pago_comprobante_de_pago_alter_pago_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante_de_pago',
            field=models.FileField(null=True, upload_to='clientes/filesbk/'),
        ),
    ]
