# Generated by Django 4.0.6 on 2022-08-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0005_pago_comprobante_de_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='nombre_cliente_pago',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_de_pago',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
