# Generated by Django 4.0.6 on 2022-08-15 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0006_pago_nombre_cliente_pago_alter_pago_fecha_de_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='cliente',
        ),
    ]
