# Generated by Django 4.0.6 on 2022-08-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0007_remove_pago_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='codigo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
