# Generated by Django 4.0.6 on 2022-08-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0008_pago_codigo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
